/**
 * report-generator.ts — Builds a real, downloadable PDF report from a fixed
 * template, entirely client-side (jsPDF + jspdf-autotable). Replaces the old
 * "Print Report" button, which just called window.print() on the live
 * dashboard page — inheriting the app chrome, on-screen chart tooltips, and
 * whatever theme happened to be active, with no real document structure.
 *
 * No server round-trip and no headless-browser dependency (Puppeteer/
 * Playwright) — this runs in the visitor's browser and triggers a native
 * file download, which keeps the self-hosted VPS deployment light. The
 * charts embedded below are rasterized from the already-rendered on-screen
 * recharts SVGs via html2canvas (in reports/page.tsx, before calling this),
 * so the PDF shows literally the same graphics as the dashboard.
 */
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { RatingItem, EventItem, Member, formatEventDateRange } from './local-data';

const BRAND_PRIMARY: [number, number, number] = [15, 42, 71]; // #0F2A47
const BRAND_ACCENT: [number, number, number] = [46, 117, 182]; // #2E75B6
const TEXT_DARK: [number, number, number] = [30, 41, 59];
const TEXT_MUTED: [number, number, number] = [100, 116, 139];
const BORDER_LIGHT: [number, number, number] = [226, 232, 240];
const PAGE_MARGIN = 40;

function scoreBand(score: number): string {
  if (score >= 4.5) return 'Excellent';
  if (score >= 3.5) return 'Good';
  if (score >= 2.5) return 'Satisfactory';
  if (score >= 1.5) return 'Needs Improvement';
  return 'Unsatisfactory';
}

function average(nums: number[]): number {
  if (nums.length === 0) return 0;
  return parseFloat((nums.reduce((a, b) => a + b, 0) / nums.length).toFixed(1));
}

function groupBy<T>(items: T[], keyFn: (item: T) => string): Map<string, T[]> {
  const map = new Map<string, T[]>();
  for (const item of items) {
    const k = keyFn(item);
    const bucket = map.get(k);
    if (bucket) bucket.push(item); else map.set(k, [item]);
  }
  return map;
}

/** Starts a new page if the given block wouldn't fit above the footer line. */
function ensureSpace(doc: jsPDF, y: number, neededHeight: number): number {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (y + neededHeight > pageHeight - 50) {
    doc.addPage();
    return 40;
  }
  return y;
}

export type ReportType = 'overall' | 'event' | 'student';

export interface CapturedChartImage {
  dataUrl: string;
  width: number;
  height: number;
}

export interface PerformanceReportParams {
  ratings: RatingItem[];
  averages: { quality: number; timeliness: number; initiative: number; collaboration: number; overall: number };
  scope: { division: string; member: string; period: string };
  generatedBy: string;
  reportType: ReportType;
  events: EventItem[];
  members: Member[];
  chartImages?: { radar?: CapturedChartImage; bar?: CapturedChartImage };
}

const REPORT_TYPE_LABEL: Record<ReportType, string> = {
  overall: 'Overall Summary (Event-wise + Student-wise Breakdown)',
  event: 'Event-wise Breakdown',
  student: 'Student-wise Breakdown',
};

export function generatePerformanceReportPdf(params: PerformanceReportParams): void {
  const { ratings, averages, scope, generatedBy, reportType, events, members, chartImages } = params;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = PAGE_MARGIN;
  let y = 0;

  // ---- Letterhead ----
  doc.setFillColor(...BRAND_PRIMARY);
  doc.rect(0, 0, pageWidth, 90, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('LEADS Next Gen Centre', margin, 38);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text('Task Performance Evaluation Report', margin, 58);
  doc.setFontSize(8.5);
  doc.setTextColor(200, 215, 230);
  doc.text('MSRUAS Portal — Confidential, Internal Use Only', margin, 74);
  y = 112;

  // ---- Metadata block ----
  doc.setTextColor(...TEXT_MUTED);
  doc.setFontSize(9);
  const generatedAt = new Date().toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' });
  const metaLines = [
    `Generated: ${generatedAt}`,
    `Generated by: ${generatedBy}`,
    `Report Type: ${REPORT_TYPE_LABEL[reportType]}`,
    `Scope: Division = ${scope.division} · Member = ${scope.member} · Period = ${scope.period}`,
    `Total Evaluations in Scope: ${ratings.length}`,
  ];
  metaLines.forEach((line, i) => doc.text(line, margin, y + i * 13));
  y += metaLines.length * 13 + 18;

  // ---- Executive summary ----
  doc.setTextColor(...TEXT_DARK);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Executive Summary', margin, y);
  y += 10;

  const summaryRows = [
    ['Quality', averages.quality, scoreBand(averages.quality)],
    ['Timeliness', averages.timeliness, scoreBand(averages.timeliness)],
    ['Initiative', averages.initiative, scoreBand(averages.initiative)],
    ['Collaboration', averages.collaboration, scoreBand(averages.collaboration)],
    ['Overall Average', averages.overall, scoreBand(averages.overall)],
  ];

  autoTable(doc, {
    startY: y + 8,
    margin: { left: margin, right: margin },
    head: [['Metric', 'Average Score (/5.0)', 'Band']],
    body: summaryRows.map(([label, score, band]) => [label, `${score} / 5.0`, band]),
    theme: 'grid',
    headStyles: { fillColor: BRAND_ACCENT, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fontSize: 9, textColor: TEXT_DARK },
    alternateRowStyles: { fillColor: [246, 249, 252] },
    didParseCell: (data) => {
      if (data.section === 'body' && data.row.index === summaryRows.length - 1) {
        data.cell.styles.fontStyle = 'bold';
      }
    },
  });

  // ---- Score distribution ----
  const bands = ['Excellent', 'Good', 'Satisfactory', 'Needs Improvement', 'Unsatisfactory'];
  const distribution = bands.map(band => ({
    band,
    count: ratings.filter(r => scoreBand(r.overallScore) === band).length,
  }));

  y = (doc as any).lastAutoTable.finalY + 22;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...TEXT_DARK);
  doc.text('Score Distribution', margin, y);

  autoTable(doc, {
    startY: y + 8,
    margin: { left: margin, right: margin },
    head: [['Performance Band', 'Evaluations', 'Share']],
    body: distribution.map(d => [
      d.band,
      String(d.count),
      ratings.length > 0 ? `${((d.count / ratings.length) * 100).toFixed(0)}%` : '0%',
    ]),
    theme: 'grid',
    headStyles: { fillColor: BRAND_PRIMARY, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fontSize: 9, textColor: TEXT_DARK },
    alternateRowStyles: { fillColor: [246, 249, 252] },
  });
  y = (doc as any).lastAutoTable.finalY + 24;

  // ---- Visual Analytics: the same charts shown on the Reports page ----
  const usableWidth = pageWidth - margin * 2;
  const chartEntries: Array<{ title: string; img: CapturedChartImage }> = [];
  if (chartImages?.radar) chartEntries.push({ title: 'Competency Balance Rubric', img: chartImages.radar });
  if (chartImages?.bar) chartEntries.push({ title: 'Deliverable Performance Distribution', img: chartImages.bar });

  if (chartEntries.length > 0) {
    y = ensureSpace(doc, y, 40);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(...TEXT_DARK);
    doc.text('Visual Analytics', margin, y);
    y += 14;

    for (const { title, img } of chartEntries) {
      const drawWidth = usableWidth;
      const drawHeight = (img.height / img.width) * drawWidth;
      y = ensureSpace(doc, y, drawHeight + 24);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9.5);
      doc.setTextColor(...TEXT_MUTED);
      doc.text(title, margin, y);
      y += 8;
      doc.addImage(img.dataUrl, 'PNG', margin, y, drawWidth, drawHeight);
      y += drawHeight + 20;
    }
  }

  // ---- Event-wise Breakdown: who contributed what, per event, pulling the
  // real event description/dates/location from the Events collection ----
  if (reportType === 'event' || reportType === 'overall') {
    const eventGroups = groupBy(ratings, r => r.eventId || r.eventName || '__standalone__');
    const sortedEventKeys = Array.from(eventGroups.keys()).sort((a, b) => {
      const nameA = eventGroups.get(a)![0].eventName || 'Standalone / No Event';
      const nameB = eventGroups.get(b)![0].eventName || 'Standalone / No Event';
      return nameA.localeCompare(nameB);
    });

    y = ensureSpace(doc, y, 40);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(...TEXT_DARK);
    doc.text(`Event-wise Breakdown (${sortedEventKeys.length} event${sortedEventKeys.length === 1 ? '' : 's'})`, margin, y);
    y += 18;

    for (const key of sortedEventKeys) {
      const eventRatings = eventGroups.get(key)!;
      const matchedEvent = events.find(e => e.id === key) || events.find(e => e.title === eventRatings[0].eventName);
      const eventName = matchedEvent?.title || eventRatings[0].eventName || 'Standalone / No Event';
      const eventAvg = average(eventRatings.map(r => r.overallScore));

      y = ensureSpace(doc, y, 60);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(...BRAND_ACCENT);
      doc.text(eventName, margin, y);
      y += 13;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(...TEXT_MUTED);
      if (matchedEvent) {
        const dateRange = formatEventDateRange(matchedEvent);
        const detailLine = [dateRange, matchedEvent.location, matchedEvent.campus].filter(Boolean).join(' · ');
        if (detailLine) {
          doc.text(detailLine, margin, y);
          y += 11;
        }
        if (matchedEvent.description) {
          const descLines = doc.splitTextToSize(matchedEvent.description, usableWidth);
          doc.text(descLines, margin, y);
          y += descLines.length * 10 + 4;
        }
      } else {
        doc.text('(Not linked to a record in the Events module)', margin, y);
        y += 11;
      }

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(...TEXT_DARK);
      doc.text(`Contributors: ${new Set(eventRatings.map(r => r.targetName)).size}  ·  Event Average: ${eventAvg} / 5.0`, margin, y);
      y += 6;

      autoTable(doc, {
        startY: y,
        margin: { left: margin, right: margin },
        head: [['Contributor', 'Task', 'Quality', 'Timeliness', 'Initiative', 'Collab.', 'Overall']],
        body: eventRatings.map(r => [
          r.targetName,
          r.taskTitle,
          r.quality.toFixed(1),
          r.timeliness.toFixed(1),
          r.initiative.toFixed(1),
          r.collaboration.toFixed(1),
          r.overallScore.toFixed(1),
        ]),
        theme: 'striped',
        styles: { fontSize: 8, cellPadding: 3.5, textColor: TEXT_DARK, lineColor: BORDER_LIGHT },
        headStyles: { fillColor: BRAND_ACCENT, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8 },
        alternateRowStyles: { fillColor: [246, 249, 252] },
      });
      y = (doc as any).lastAutoTable.finalY + 20;
    }
  }

  // ---- Student-wise Breakdown: every student's tasks/events/ratings ----
  if (reportType === 'student' || reportType === 'overall') {
    const studentGroups = groupBy(ratings, r => r.targetId || r.targetName);
    const sortedStudentKeys = Array.from(studentGroups.keys()).sort((a, b) => {
      return studentGroups.get(a)![0].targetName.localeCompare(studentGroups.get(b)![0].targetName);
    });

    y = ensureSpace(doc, y, 40);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(...TEXT_DARK);
    doc.text(`Student-wise Breakdown (${sortedStudentKeys.length} member${sortedStudentKeys.length === 1 ? '' : 's'})`, margin, y);
    y += 18;

    for (const key of sortedStudentKeys) {
      const studentRatings = studentGroups.get(key)!;
      const targetName = studentRatings[0].targetName;
      const member = members.find(m => m.id === key || m.name === targetName);
      const studentAvg = average(studentRatings.map(r => r.overallScore));

      y = ensureSpace(doc, y, 50);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(...BRAND_ACCENT);
      doc.text(targetName, margin, y);
      y += 13;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(...TEXT_MUTED);
      const memberLine = member ? [member.division, member.role].filter(Boolean).join(' · ') : 'Not currently on the roster';
      doc.text(memberLine, margin, y);
      y += 11;

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(...TEXT_DARK);
      doc.text(`Evaluations: ${studentRatings.length}  ·  Personal Average: ${studentAvg} / 5.0`, margin, y);
      y += 6;

      autoTable(doc, {
        startY: y,
        margin: { left: margin, right: margin },
        head: [['Event', 'Task', 'Evaluator', 'Quality', 'Timeliness', 'Initiative', 'Collab.', 'Overall']],
        body: studentRatings.map(r => [
          r.eventName || 'Standalone',
          r.taskTitle,
          r.raterName,
          r.quality.toFixed(1),
          r.timeliness.toFixed(1),
          r.initiative.toFixed(1),
          r.collaboration.toFixed(1),
          r.overallScore.toFixed(1),
        ]),
        theme: 'striped',
        styles: { fontSize: 8, cellPadding: 3.5, textColor: TEXT_DARK, lineColor: BORDER_LIGHT },
        headStyles: { fillColor: BRAND_PRIMARY, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8 },
        alternateRowStyles: { fillColor: [246, 249, 252] },
      });
      y = (doc as any).lastAutoTable.finalY + 20;
    }
  }

  // ---- Detailed audit log (appendix, new page for a clean start) ----
  doc.addPage();
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...TEXT_DARK);
  doc.text('Appendix: Full Audited Performance Log', margin, 40);

  autoTable(doc, {
    startY: 52,
    margin: { left: margin, right: margin },
    head: [['Student', 'Task', 'Event', 'Evaluator', 'Month', 'Qual.', 'Time.', 'Init.', 'Collab.', 'Overall', 'Date', 'Remarks']],
    body: ratings.map(r => [
      r.targetName,
      r.taskTitle,
      r.eventName || '—',
      r.raterName,
      (r.createdAt || '').slice(0, 7),
      r.quality.toFixed(1),
      r.timeliness.toFixed(1),
      r.initiative.toFixed(1),
      r.collaboration.toFixed(1),
      r.overallScore.toFixed(1),
      (r.createdAt || '').split('T')[0],
      r.notes || '—',
    ]),
    theme: 'striped',
    styles: { fontSize: 7.5, cellPadding: 4, textColor: TEXT_DARK, lineColor: BORDER_LIGHT },
    headStyles: { fillColor: BRAND_PRIMARY, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 7.5 },
    alternateRowStyles: { fillColor: [246, 249, 252] },
    columnStyles: {
      1: { cellWidth: 70 },
      2: { cellWidth: 55 },
      11: { cellWidth: 80 },
    },
  });

  // ---- Footer on every page ----
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setDrawColor(...BORDER_LIGHT);
    doc.line(margin, pageHeight - 34, pageWidth - margin, pageHeight - 34);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...TEXT_MUTED);
    doc.text('LEADS Next Gen Centre — Confidential', margin, pageHeight - 20);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 20, { align: 'right' });
  }

  const stamp = new Date().toISOString().split('T')[0];
  doc.save(`leads_performance_report_${reportType}_${stamp}.pdf`);
}
